### PR TITLE
Update publish.yaml

### PR DESCRIPTION
**Pull request by anycodes**
- 更新分类：基础云服务->开源项目
- 更新服务选项：可以注释掉这部分

### CODE REVIEW

**Comment by webup** [comment]
@anycodes thanks for the PR, please sign DCO so we could move on. :)

**Comment by anycodes** [comment]
Signed-off-by: anycodes [service@anycodes.cn](mailto:service@anycodes.cn)

**Comment by benjaminhuo** [comment]
To sign the commit, you'll need to:
```shell
git commit -s --amend
git push -f
```

**Comment by webup** [comment]
@all-contributors please add @anycodes for content

**Comment by webup** [comment]
https://github.com/all-contributors please add @anycodes for content

**Comment by webup** [comment]
@all-contributors please add @anycodes for content

**Comment by webup** [comment]
@all-contributors please add @anycodes for content modification

**Pull request merged**
